### ISSUE TITLE
shift clicking still crashes server

### ISSUE THREAD

**Issue by xlis1** [Jikoo/PortableShulkerBox#1]
as the title says shift clicking items still crashes server in 1.12

i attached the logfile

[2017-07-15-12.log.gz](https://github.com/Jikoo/PortableShulkerBox/files/1150809/2017-07-15-12.log.gz)

**Comment by Jikoo** [comment]
Please replicate this using release version 1.0.0 - you're using a version compiled goodness knows when or how, certainly not by myself.

**Comment by xlis1** [comment]
it was a version compiled by me that fixed the bug where un-renamed shulker boxes could not be opened, however, i just tested with v1.0.0 from GitHub and got the same crash




[latest.zip](https://github.com/Jikoo/PortableShulkerBox/files/1150814/latest.zip)

**Comment by Jikoo** [comment]
Interesting. Can you provide steps for replicating? Also, oops about unnamed boxes, will fix that.

**Comment by xlis1** [comment]
i just put a bunch of stuff in a box and shift click it in and out quickly until the server crashes, not really all that complected.

**Comment by Jikoo** [comment]
Betting it's clicking hotbar slots, whoops. Little bit of an oversight.

**Comment by Jikoo** [comment]
[1.0.1](https://github.com/Jikoo/PortableShulkerBox/releases/tag/v1.0.1) should work, tested it and can't manage to cause crashes now. Unnamed boxes also work.

**Comment by xlis1** [comment]
Works perfectly now. Thank you, closing issue.
